# 12 busieset US Airports
Airport.create(code: 'ATL')
Airport.create(code: 'LAX')
Airport.create(code: 'ORD')
Airport.create(code: 'DFW')
Airport.create(code: 'JFK')
Airport.create(code: 'DEN')
Airport.create(code: 'SFO')
Airport.create(code: 'LAS')
Airport.create(code: 'CLT')
Airport.create(code: 'SEA')
Airport.create(code: 'PHX')
Airport.create(code: 'MIA')
